//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourProjectName_Data.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DTB_ICMS_CREDIT_DEVEntities : DbContext
    {
        public DTB_ICMS_CREDIT_DEVEntities()
            : base("name=DTB_ICMS_CREDIT_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<parameter> parameter { get; set; }
        public virtual DbSet<plant> plant { get; set; }
        public virtual DbSet<security_area> security_area { get; set; }
        public virtual DbSet<security_role> security_role { get; set; }
        public virtual DbSet<security_task> security_task { get; set; }
        public virtual DbSet<security_user> security_user { get; set; }
        public virtual DbSet<vw_example> vw_example { get; set; }
    
        public virtual int sp_User_Delete(Nullable<int> iduser)
        {
            var iduserParameter = iduser.HasValue ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_User_Delete", iduserParameter);
        }
    }
}
