//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourProjectName_Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class parameter
    {
        public int idparameter { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public string description { get; set; }
        public string plant_id { get; set; }
    
        public virtual plant plant { get; set; }
    }
}
