//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourProjectName_Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class security_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public security_user()
        {
            this.plant1 = new HashSet<plant>();
            this.security_role = new HashSet<security_role>();
        }
    
        public int iduser { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public int idarea { get; set; }
        public string plant_id { get; set; }
    
        public virtual plant plant { get; set; }
        public virtual security_area security_area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plant> plant1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<security_role> security_role { get; set; }
    }
}
